%--------------------------------------------------------------------------
% Script for mex compilation of C++ files. Use with care. 
%
% With great power comes great responsibility.
%
% Author: BLB
% Version: 1.0
% Year: 2015
%--------------------------------------------------------------------------
% Define some paths
gslpath         = '-I/lib/gsl';
incpath         = '-I/C';
libgslpath      = 'lib/libgsl.a';
libgslcblaspath = 'lib/libgslcblas.a';
                   
%% Build cumovec.cpp
mex(gslpath, 'cumovec.cpp', libgslpath,... 
                            libgslcblaspath, ...
                          'Cpp/FTA.cpp',...
                          'Cpp/Oftsc.cpp',...
                          'Cpp/Ofsc.cpp',...
                          'Cpp/pmcoc.cpp',...
                          'Cpp/vf.cpp',...
                          'Cpp/ode.cpp',...
                          'Cpp/nrutil.c',...
                          'Cpp/single_orbit.cpp',...
                          'Cpp/eminsem.cpp',...
                          'Cpp/env.cpp');       
                      
%% Build cmic.cpp
mex(gslpath, 'cmic.cpp', libgslpath,... 
                         libgslcblaspath, ...
                         'Cpp/FTA.cpp',...
                         'Cpp/Oftsc.cpp',...
                         'Cpp/Ofsc.cpp',...
                         'Cpp/pmcoc.cpp',...
                         'Cpp/env.cpp');                    
 

%% Build cumo.cpp
mex(gslpath, 'cumo.cpp', libgslpath,... 
                          libgslcblaspath, ...
                          'Cpp/FTA.cpp',...
                          'Cpp/Oftsc.cpp',...
                          'Cpp/Ofsc.cpp',...
                          'Cpp/pmcoc.cpp',...
                          'Cpp/vf.cpp',...
                          'Cpp/ode.cpp',...
                          'Cpp/nrutil.c',...
                          'Cpp/single_orbit.cpp',...
                          'Cpp/env.cpp');
                      
%% Build cmo.cpp
mex(gslpath, 'cmo.cpp', libgslpath,... 
                          libgslcblaspath, ...
                          'Cpp/FTA.cpp',...
                          'Cpp/Oftsc.cpp',...
                          'Cpp/Ofsc.cpp',...
                          'Cpp/pmcoc.cpp',...
                          'Cpp/vf.cpp',...
                          'Cpp/ode.cpp',...
                          'Cpp/nrutil.c',...
                          'Cpp/single_orbit.cpp',...
                          'Cpp/env.cpp');
                      
                      

%% Build test.cpp
mex(gslpath, 'test.cpp', libgslpath,... 
                         libgslcblaspath);
                                